# Generated by Django 3.2.9 on 2021-11-06 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('about', models.CharField(max_length=500)),
            ],
            options={
                'unique_together': {('first_name', 'last_name')},
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название книги')),
                ('description', models.TextField(max_length=350, verbose_name='Описание книги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('genre', models.CharField(choices=[('Adventure', 'Adventure'), ('Detective', 'Detective'), ('Romance', 'Romance'), ('Classics', 'Classics'), ('Fantasy', 'Fantasy'), ('Poetry', 'Poetry')], default='Classics', max_length=20, verbose_name='Жанр')),
                ('rating', models.FloatField(verbose_name='Рейтинг')),
                ('available', models.BooleanField(default=True)),
                ('author', models.ManyToManyField(related_name='Автор', to='stock.Author')),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.book')),
            ],
        ),
    ]
